[workspace]
resolver = "2"
members = ["crates/invars"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/lsalenson/invars"
authors = ["LÃ©o Salenson <leo.salenson@outlook.fr>"]
description = "Data invariants for Polars."
version = "0.0.1"