[package]
name = "invar_polars"
version = "0.1.0"
edition = "2024"

[dependencies]
invar_domain = { path="../invar_domain" }
invar_application = { path="../invar_application" }
polars = { version = "0.53.0", features = [
    "lazy",
    "fmt",
] }