[package]
name = "invars_application"
publish = false
license = "MIT"
version = "0.0.1"
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
invars_domain = { workspace = true }