[package]
name = "invars_polars"
version = "0.0.1"
edition = "2024"

[dependencies]
invars_domain = { path= "../invars_domain" }
invars_application = { path= "../invars_application" }
polars = { version = "0.53.0", features = [
    "lazy",
    "fmt",
] }