[package]
name = "invar"
version = "0.1.0"
edition = "2024"

[dependencies]
invar_domain = { path = "../invar_domain" }
invar_application = { path = "../invar_application" }
invar_polars = { path = "../invar_polars", optional = true }

[features]
default = ["polars"]
polars = ["invar_polars"]
